---
apiVersion: v1
kind: Service
metadata:
  name: plex-docker
  namespace: networking
spec:
  type: ExternalName
  ports:
    - name: https
      port: 32400
      targetPort: 32400
  externalName: 192.168.5.10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-docker
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
spec:
  ingressClassName: external
  tls:
    - hosts:
        - plex.${SECRET_DOMAIN}
  rules:
    - host: plex.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex-docker
                port:
                  number: 32400
