---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: networking
spec:
  type: ExternalName
  ports:
    - name: https
      port: 8006
      targetPort: 8006
  externalName: 192.168.5.10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - proxmox.${SECRET_DOMAIN}
  rules:
    - host: proxmox.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxmox
                port:
                  number: 8006
