---
apiVersion: v1
kind: Service
metadata:
  name: unifi-router
  namespace: networking
spec:
  type: ExternalName
  ports:
    - name: https
      port: 443
      targetPort: 443
  externalName: 192.168.5.1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-router
  namespace: networking
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - unifi.${SECRET_DOMAIN}
  rules:
    - host: unifi.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi-router
                port:
                  number: 443
