---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.0.1
    ports:
      - name: https
        port: 443
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: networking
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - unifi.${SECRET_DOMAIN}
  rules:
    - host: unifi.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi
                port:
                  number: 443
