apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: mirioeggmann/cloudflare-ddns:v0.5.1
              envFrom:
                - secretRef:
                    name: cloudflare-ddns-secret
          restartPolicy: OnFailure
