---
# Area
- name: area/ansible
  color: "0e8a16"
  description: >-
    Changes made in the ansible directory
- name: area/github
  color: "0e8a16"
  description: >-
    Changes made in the github directory
- name: area/kubernetes
  color: "0e8a16"
  description: >-
    Changes made in the kubernetes directory
- name: area/bootstrap
  color: "0e8a16"
  description: >-
    Changes made in the bootstrap directory
- name: area/terraform
  color: "0e8a16"
  description: >-
    Changes made in the terraform directory
# Renovate
- name: renovate/ansible
  color: "027fa0"
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/helm
  color: "027fa0"
- name: renovate/terraform
  color: "027fa0"
# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
# Uncategorized
- name: hold/upstream
  color: "ee0701"
