---
- name: Proxmox Dockerize | Cadvisor | Create cadvisor directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ apps_dir }}/cadvisor"

- name: Proxmox Dockerize | Cadvisor | Copy cadvisor docker compose file
  ansible.builtin.template:
    src: cadvisor/docker-compose.yml.j2
    dest: "{{ apps_dir }}/cadvisor/docker-compose.yml"
    mode: 0755
  register: compose

- name: Proxmox Dockerize | Cadvisor | Create cadvisor systemd file
  ansible.builtin.template:
    src: "docker-compose@.service.j2"
    dest: "/etc/systemd/system/docker-compose@cadvisor.service"
    mode: 0644
  register: systemd

- name: Proxmox Dockerize | Cadvisor | Start and enable cadvisor
  ansible.builtin.systemd:
    name: "docker-compose@cadvisor.service"
    state: restarted
    enabled: true
    daemon_reload: true
  when: compose.changed or systemd.changed or 'cadvisor' not in running_containers.stdout
