---
- name: Proxmox Dockerize | Create default directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: '0755'
  loop:
    - /storage/docker
    - "{{ apps_dir }}"
    - "{{ data_dir }}"

- name: Proxmox Dockerize | Register running containers
  ansible.builtin.shell: docker container ls -a
  register: running_containers
  changed_when: false
  failed_when: false
  check_mode: false
  ignore_errors: true

- name: Proxmox Dockerize | Prometheus PVE Exporter
  ansible.builtin.include_tasks: prometheus-pve-exporter.yml
  tags:
    - prometheus-pve-exporter
- name: Proxmox Dockerize | Promtail
  ansible.builtin.include_tasks: promtail.yml
  tags:
    - promtail
- name: Proxmox Dockerize | Plex
  ansible.builtin.include_tasks: plex.yml
  tags:
    - plex
- name: Proxmox Dockerize | Docker Cleanup
  ansible.builtin.include_tasks: docker.yml
  tags:
    - docker
