---
- name: Proxmox Dockerize | Node Exporter | Create node-exporter directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ apps_dir }}/node-exporter"

- name: Proxmox Dockerize | Node Exporter | Copy node-exporter docker compose file
  ansible.builtin.template:
    src: node-exporter/docker-compose.yml.j2
    dest: "{{ apps_dir }}/node-exporter/docker-compose.yml"
    mode: 0755
  register: compose

- name: Proxmox Dockerize | Node Exporter | Create node-exporter systemd file
  ansible.builtin.template:
    src: "docker-compose@.service.j2"
    dest: "/etc/systemd/system/docker-compose@node-exporter.service"
    mode: 0644
  register: systemd

- name: Proxmox Dockerize | Node Exporter | Start and enable node-exporter
  ansible.builtin.systemd:
    name: "docker-compose@node-exporter.service"
    state: restarted
    enabled: true
    daemon_reload: true
  when: compose.changed or systemd.changed or 'node-exporter' not in running_containers.stdout
