---
- name: Proxmox Dockerize | Plex | Create plex directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ apps_dir }}/plex"

- name: Proxmox Dockerize | Plex | Copy plex docker compose file
  ansible.builtin.template:
    src: plex/docker-compose.yml.j2
    dest: "{{ apps_dir }}/plex/docker-compose.yml"
    mode: 0755
  register: compose

- name: Proxmox Dockerize | Plex | Create plex systemd file
  ansible.builtin.template:
    src: "docker-compose@.service.j2"
    dest: "/etc/systemd/system/docker-compose@plex.service"
    mode: 0644
  register: systemd

- name: Proxmox Dockerize | Plex | Start and enable plex
  ansible.builtin.systemd:
    name: "docker-compose@plex.service"
    state: restarted
    enabled: true
    daemon_reload: true
  when: compose.changed or systemd.changed or 'plex' not in running_containers.stdout
