---
- name: Proxmox Dockerize | Promtail | Create promtail directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ apps_dir }}/promtail"
    - "{{ data_dir }}/promtail"

- name: Proxmox Dockerize | Promtail | Copy promtail docker compose file
  ansible.builtin.template:
    src: promtail/docker-compose.yml.j2
    dest: "{{ apps_dir }}/promtail/docker-compose.yml"
    mode: 0755
  register: compose

- name: Proxmox Dockerize | Promtail | Copy promtail config
  ansible.builtin.template:
    src: promtail/promtail.yaml.j2
    dest: "{{ apps_dir }}/promtail/promtail.yaml"
    mode: 0755
  register: config

- name: Proxmox Dockerize | Promtail | Create promtail systemd file
  ansible.builtin.template:
    src: "docker-compose@.service.j2"
    dest: "/etc/systemd/system/docker-compose@promtail.service"
    mode: 0644
  register: systemd

- name: Proxmox Dockerize | Promtail | Start and enable promtail
  ansible.builtin.systemd:
    name: "docker-compose@promtail.service"
    state: restarted
    enabled: true
    daemon_reload: true
    started: true
  when: compose.changed or config.changed or systemd.changed or 'promtail' not in running_containers.stdout
