---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-slow
  labels:
    disk.home.arpa/fs: zfs
    disk.home.arpa/type: hdd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.5.10
  share: /storage
  subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
# Note: The first two options are strictly for NFSv4.2
mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-fast
  labels:
    disk.home.arpa/fs: zfs
    disk.home.arpa/type: ssd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.5.10
  share: /storage-fast
  subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
# Note: The first two options are strictly for NFSv4.2
mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
