apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
stringData:
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:zBGhfYOJb9CLSu07a1frfffayf6XMfVE,iv:kZ4g5UUBjy23b6PbJgvValWXebpSgyBnKxEA1zKY9VE=,tag:X1MMmFiuRV7bqtqEWK4Z/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1meu65v2nuw6ntzn8fghgc59mmkcm2uhynj4ydchrpdp6audq2y6q85kadn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R0d0cVZKWTlxV2xrSE5H
            MWRWM2ZneUdrY0ZiNUdOeFBUVzRqSUNXZUFNCitpODdFdTFIalpWWE5seGpiWHN5
            V1dBWmQ5eEQzQXNSak5xMEc2QmdFdm8KLS0tIFZxRzA2aXJhQ1RncXl1N3FTa2t2
            bCt2WExZWXVaNjIwYnJLNWVpSllaUE0K4pFWidEQFmDqs4mz6IKDbnQHU2m8m1mg
            lVgKCjKSZNE10GvqUzWWAZ7p1yrliD4yY3NS8fBt5FoOJTV1UiHJWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T19:04:13Z"
    mac: ENC[AES256_GCM,data:9Oif4Q1mcdtIbB6eFu7l8L/P0FHiCqboUX+1hhWPmQdJwpyd6Iu2HE+DVWla50w3m/306TLvk2G/atu/IVbO9mmxd+Xa+/tSMeUdnY67ZAmiNuJtOK2G4GOQA0+nCcW59XsPOMG6ZyQfDtonlaQ0MOjGKSoV7/rB/QeQHs0t/R8=,iv:CyrVS+SrZLwCEhXK/Q95DLyPS8MU5aVDHO6Qw+Jwr6k=,tag:+Hs4UQ1o3zDwK1BJevz1+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
