apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:VyjW6q60jo8WdF5hni3ibUezdxo83JsB,iv:iv+hMrMesqNMyuEgKnbsmqH54HQpBh6d3p1Wl25P9Yo=,tag:v/ovuLRF4c/F5XA+PfIFWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1meu65v2nuw6ntzn8fghgc59mmkcm2uhynj4ydchrpdp6audq2y6q85kadn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiek5VOEE1Z3NmWU8yVWFp
            VXpXQU9oYkRGZnpHTFl1c3FSV21mdGpWUGs4CkREb1ppcDc1RDBIa0lCUlEvWVB6
            aXI1YkpBazl2VDZ5MGdiZ3lFWGMwY2sKLS0tIGViOUVGU2szai9zUHF4bnd2V0o1
            RlRYeEN6bk03R1FzS2Z0SHA5aHFLWHcKCVQayhUAOeWY42IC8NvdMbpYSEEid0x0
            Gm3MruUpL4FAY1S+MF+2LLHRJQ+/TDNsDJqVonK1qu0odjhmzx798A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T17:05:04Z"
    mac: ENC[AES256_GCM,data:QS8+apFibZKUgBqUrsmpwUeSS9hX6KNcBhvLiwqLn8D3elR9MtW56zHPQYijUSFO66Q/hfuXcByZ4kQOy+K+EujYW/20avySUd+WomY0FtI3XgqfpH7pU/GRb9GW3i4Ewo1Id5tj9sCuWkw7IuS3n8UHQE32FNbs5VK2/xw+gqw=,iv:VDWd7McTQVQwydNBtgu0xrkg64XEAYvY7G+E9vNzZMo=,tag:1MTiiIms83poRsCrwyKSjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
