# This assumes we're using Proxmox 8 running on Debian 12 (Bookworm)
---
- name: Proxmox Configs | Apt Sources | Add non-free packages and backports to debian sources
  ansible.builtin.copy:
    dest: /etc/apt/sources.list
    content: |
      # non-free-firmware required for intel microcode
      deb http://ftp.debian.org/debian bookworm main contrib non-free non-free-firmware
      deb http://ftp.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
      # security updates
      deb http://security.debian.org/debian-security bookworm-security main contrib
    mode: '0644'

- name: Proxmox Configs | Apt Sources | Create Proxmox community source file
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list.d/pve-community.list
    create: true
    mode: '0644'
    block: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

- name: Proxmox Configs | Apt Sources | Remove Proxmox enterprise repo from sources
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb .*pve bookworm pve-enterprise$'
    replace: '# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
