---
- name: Proxmox Configs | NFS Server | Setup NFS server config
  ansible.builtin.copy:
    dest: /etc/exports
    content: |
      # SSD storage - limited to k3s nodes
      /storage-fast 192.168.5.64/26(rw,sync,no_subtree_check,no_root_squash)
      # General storage - limited to k3s nodes
      /storage 192.168.5.64/26(rw,sync,no_subtree_check,no_root_squash)
      # Plex media storage - general availability
      /storage/plex-data *(rw,sync,no_subtree_check,all_squash,anonuid=1001,anongid=1001)
  register: nfs_server_config

# TODO: Clean this up
# - name: Proxmox Configs | NFS Server | Mount fast storage SSD
#   mkdir /storage-fast
#   mount -U 81fef8f6-d48a-487a-b92f-10c01447fb2e /storage-fast
#   echo "UUID=81fef8f6-d48a-487a-b92f-10c01447fb2e /storage-fast ext4 defaults 0 0" >> /etc/fstab
