---
- name: Proxmox Configs | Packages | Upgrade all system packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: Proxmox Configs | Packages | Install common packages
  ansible.builtin.apt:
    name:
      - apcupsd
      - arptables
      - bash-completion
      - ca-certificates
      - cryptsetup
      - curl
      - iputils-ping
      - ipvsadm
      - libguestfs-tools
      - libsasl2-modules
      - lvm2
      - net-tools
      - nfs-common
      - nfs-kernel-server
      - psmisc
      - python3-pip
      - restic
      - screen
      - smartmontools
      - sysstat
      - software-properties-common
      - unattended-upgrades
      - unzip
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

- name: Proxmox Configs | Packages | Install microcode
  ansible.builtin.apt:
    name:
      - intel-microcode
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

- name: Proxmox Configs | Packages | Copy 20auto-upgrades unattended-upgrades config
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
    create: true
    block: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";

- name: Proxmox Configs | Packages | Copy 50unattended-upgrades unattended-upgrades config
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
    create: true
    block: |
      Unattended-Upgrade::Automatic-Reboot "false";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id} stable";
          "${distro_id} ${distro_codename}-security";
          "${distro_id} ${distro_codename}-updates";
      };

- name: Proxmox Configs | Packages | Start unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

- name: Proxmox Configs | Packages | Restart unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades.service
    daemon_reload: true
    enabled: true
    state: restarted

# TODO: install prom exporter for proxmox
# https://github.com/prometheus-pve/prometheus-pve-exporter
