---
- name: Proxmox Configs | Node Exporter
  block:
    - name: Proxmox Configs | Node Exporter | Download tarball
      ansible.builtin.get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp
      vars:

    - name: Proxmox Configs | Node Exporter | Unarchive
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp

    - name: Proxmox Configs | Node Exporter | Move to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        remote_src: true
        owner: root
        group: root
        mode: 0755

    - name: Proxmox Configs | Node Exporter | Install unit file to systemd
      ansible.builtin.copy:
        dest: /etc/systemd/system/node-exporter.service
        owner: root
        group: root
        mode: 0644
        content: |
          # Ansible managed
          [Unit]
          Description=Node Exporter
          After=network.target
          [Service]
          Type=simple
          User=nobody
          Group=nogroup
          ExecStart=/usr/local/bin/node_exporter
          SyslogIdentifier=node_exporter
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: Proxmox Configs | Node Exporter | Configure systemd to use service
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        state: started
        name: node-exporter.service
  vars:
    node_exporter_version: 1.7.0

- name: Proxmox Configs | cAdvisor
  block:
    - name: Proxmox Configs | cAdvisor | Download binary
      ansible.builtin.get_url:
        url: https://github.com/google/cadvisor/releases/download/v{{ cadvisor_version }}/cadvisor-v{{ cadvisor_version }}-linux-amd64
        dest: /tmp
      vars:

    - name: Proxmox Configs | cAdvisor | Move to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/cadvisor-v{{ cadvisor_version }}-linux-amd64
        dest: /usr/local/bin/cadvisor
        remote_src: true
        owner: root
        group: root
        mode: 0755

    - name: Proxmox Configs | cAdvisor | Install unit file to systemd
      ansible.builtin.copy:
        dest: "/etc/systemd/system/cadvisor.service"
        mode: 0644
        content: |
          # Ansible managed
          [Unit]
          Description=cAdvisor Exporter
          After=network.target
          [Service]
          Type=simple
          User=nobody
          Group=nogroup
          ExecStart=/usr/local/bin/cadvisor
          SyslogIdentifier=cadvisor
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: Proxmox Configs | cAdvisor | Configure systemd to use service
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        state: started
        name: cadvisor.service
  vars:
    cadvisor_version: 0.47.2

- name: Proxmox Configs | PVE Exporter
  block:
    - name: Proxmox Configs | PVE Exporter | Setup virtualenv
      ansible.builtin.pip:
        name: prometheus-pve-exporter=={{ pve_exporter_version }}
        virtualenv: /opt/pve-exporter
        virtualenv_site_packages: false
        virtualenv_command: 'python3 -m venv'

    - name: Proxmox Configs | PVE Exporter | Install config file
      ansible.builtin.copy:
        dest: "/etc/pve-exporter.yml"
        content: "{{ lookup('community.sops.sops', 'prometheus-pve-exporter.yml.sops') }}"
        mode: '0600'

    # TODO: change this from nobody to proper service accounts
    - name: Proxmox Configs | PVE Exporter | Install unit file to systemd
      ansible.builtin.copy:
        dest: "/etc/systemd/system/pve-exporter.service"
        mode: 0644
        content: |
          # Ansible managed
          [Unit]
          Description=PVE Exporter
          After=network.target
          [Service]
          Type=simple
          User=nobody
          Group=nogroup
          ExecStart=/opt/pve-exporter/bin/pve_exporter --config.file /etc/pve-exporter.yml
          SyslogIdentifier=pve-exporter
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: Proxmox Configs | PVE Exporter | Configure systemd to use service
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        state: started
        name: pve-exporter.service
  vars:
    pve_exporter_version: 3.0.2

- name: Proxmox Configs | Smartctl Exporter
  block:
    - name: Proxmox Configs | Smartctl Exporter | Download binary
      ansible.builtin.get_url:
        url: https://github.com/prometheus-community/smartctl_exporter/releases/download/v{{ smartctl_exporter_version }}/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp

    - name: Proxmox Configs | Smartctl Exporter | Unarchive
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp

    - name: Proxmox Configs | Smartctl Exporter | Move to /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64/smartctl_exporter
        dest: /usr/local/bin/smartctl_exporter
        remote_src: true
        owner: root
        group: root
        mode: 0755

    # TODO: change this from nobody to proper service accounts
    - name: Proxmox Configs | Smartctl Exporter | Install unit file to systemd
      ansible.builtin.copy:
        dest: "/etc/systemd/system/smartctl-exporter.service"
        mode: 0644
        content: |
          # Ansible managed
          [Unit]
          Description=Smartctl Exporter
          After=network.target
          [Service]
          Type=simple
          User=root
          ExecStart=/usr/local/bin/smartctl_exporter
          SyslogIdentifier=smartctl_exporter
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: Proxmox Configs | Smartctl Exporter | Configure systemd to use service
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        state: started
        name: smartctl-exporter.service
  vars:
    smartctl_exporter_version: 0.11.0
