apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:syBsQOGXdN5EH2zmPx2OPMud6Q45U9Lu+RbsmXn6Kdc=,iv:3tzZGeVN9YF6h3nVU53nz/bEKFNquZyaLzI2ipea6v8=,tag:sgQPULE8jtQjcfCp3xc6fQ==,type:str]
    LLDAP_LDAP_USER_DN: ENC[AES256_GCM,data:j2HjS13LOg==,iv:KPiOt/TUGqoErq8m/oyIq+upbKjxdUkdrl3mZjIfwjQ=,tag:kdcFLwzHYzpK8RPUDqwUZw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:lfIbG+cpvE1shByg,iv:3pt5ZRhP3oK+dZN2uMFxhHpPax50R5Imcgh8mMYS0ds=,tag:j1SRUVYZTySGZJBaYs6CjQ==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:C/A+CkZCBKa8tDPm8zYkF2o=,iv:8ahlXC0HFUM7oN0MtpjvHN7wbmNHYQYefxPz+/Hs5JU=,tag:gQ+Nm0z/O0WoiulpyeLRcQ==,type:str]
    LLDAP_KEY_SEED: ENC[AES256_GCM,data:xsmJJ7Sesp5MD1P3p0PlMl5bLGtY5mnF6iNw0U+uDOrZ3aa1gBwemw==,iv:4Th+qRcQe0t4BfclUswRVtnCrxxi71ammR/ckEIFWf8=,tag:hmVc+8bIy0pTUuaWqnBuwg==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:faPM373nkFddiOmxhbnSB7g7QjnC9/Z7gxwK9BLlMYMAzdh2RqzexSN90jiZpy1tm/wlifJqqrQqk+ufsaej2/SckMc9IQEy7MEkQNUWIJ47VP8ynboiXnY=,iv:9SqszxtFIFKgO8qcKgpHRVMq1vCCgh9smsQoAJAfwUE=,tag:9s4tt1yy9oCLvb9UynKxng==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UTrdfqI=,iv:SUAe1aoqDmO2besz69RQVqC56EMN3hRABUC5Y/p9qso=,tag:d8YADfT0VYKFwCt3cvNpdA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HkJ3+PDBlI2qhfJJP4bH5CJKap4EHlmPg++tv52NG/4w5nI7gYYIRGE=,iv:VWpAxDfIwckOodn164UXG8TjUHuwjuL1MSzLLAC84ug=,tag:s+g/RMXPNyp/GC+XeEtrBQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:gaLFQeo=,iv:1xM19NGul88JggZ+dROsxvlLKshkEubrvxeaQpes4Bk=,tag:gF1OdKWdG0eqghma4aOZBw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:aqC3eUBsyGB54HGbTAPOS4Es2bg8UNNN,iv:ibBx/WW0v4bjqTqUMj4hHsZuDFI8kwDW6F9Ows5CMQI=,tag:4YoCRSkQbBRdC2Q+qgCb2A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:618ddUJ78DEpbw3T,iv:qXXbt6juRaKS/AlnppGvUjyW7XyJwRGEPOMGIzps7yk=,tag:lD/NQV/kCIhNVAWSkIFS1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1meu65v2nuw6ntzn8fghgc59mmkcm2uhynj4ydchrpdp6audq2y6q85kadn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL2V6YmkvMENJeklRNGpH
            SmNMaGF2UHcwTmU0WXZVdjQ4TzFUNWdRa1c0CkJSejB4WTlxcDJFOWFxWFc4Z0Fw
            YWNzcVNrSys0djBXbkNuejNlWStMWkUKLS0tIGxmMFRxcWxpL3R2alYxeEp5Z0ZN
            THlZZ0VSWHFqQldDalF3ck42TXZLVEEKXlKguZ5bjk8F/pOhwyxIirPCmlGlKEsV
            un/HLZiRH6IPVOFq8o8hkfmILNvFH2KwP3sWRip/46Z7lUU5G9SiEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T18:25:54Z"
    mac: ENC[AES256_GCM,data:qtu/ToHN68xd8Nc6nJGM6yGtPgG+/N4qoNnA8hCrgJoyxauDk/iKBZj3ONkrvoV1YAjpJQtAO5M6q/JcUMhCK/kg4jgb1j7Mm4NGq3IrimEWmcDiy4l7Epfj3valwKQyQ9EY3vQQ8b+GSd3wjxodeZBvkT9BbXvo/RFDtFSVLdM=,iv:dEklP8rlEVumjYczw2hrpD10uby9e6mw99ga4JVEV/0=,tag:R+f89vpPBuZCA4BjVtNxag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
