---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: authentication
spec:
  storageClassName: nfs-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
