# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: authentication
type: Opaque
stringData:
    adminToken: ENC[AES256_GCM,data:z7qihUDXcIiNUy2Vzumki1URuF3rTGwrBhIt1CtJ+jOU16uT,iv:bMCKDsDseAu2pxpDSzhwPDfZigLWlPVjc9k0dLdNkGI=,tag:WoaG8X7Zmnu+4uqe718F5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uks2xtgfcjk5cfzv40jm3ar9yl3jzdpea0jcta9zsa00td0r8shqx07umn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd1l4QVZuQ2RCcnZBakFo
            ZkNPYklrNzI4VU5SeVJmUUY2dUhhWWdRYjNBCnMzSHRTOUhkcW11eWFsdWxrTmRN
            bFVzTkt2RTNPL2dXc0xGV0Y1dlhMUXcKLS0tIEYrOFVFMFJnUHppc2pHcDV1V1dF
            TU5XdmU1enZCSURXZVJYZ29VbEI4MWMKhaS7jpi5nC1VkEDpPEV+exMZh+79iEZF
            HOeWAoYCoiNnGKR/W9Zc5OBst0AHZA3Nz1j0GM0rLgj7qDPuID3qXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-21T22:47:21Z"
    mac: ENC[AES256_GCM,data:fklr5nJU1fjIrD6wo+NQ0pR0dJFgk/W4BTMITb7+ANl0oEyZ6gjMCc3b35+sE2Gu1LBheVtUqmy1mTmQG9OWGunr2nwkLBHFGb+/A0HF2hHBl0ePgaXuUZnJGtT0/dQ+eBa3hR5dE5uNyxHkErc0Ex42QlS4djjagTF1QYNrfo8=,iv:dcIcWo/B0NrILdr1p7HYpiPDbLmloEH2eUiySx7WSyI=,tag:b+/C4gBnA09V0nK+MQokbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
