apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: authentication
type: Opaque
stringData:
    adminToken: ENC[AES256_GCM,data:iezdq6GzCmSCTTBCqxtbBZ9LhbWz+I8pKKMJExBcqVzLRSGn+1j2M0KPYVQ=,iv:ZVxqD+8/yVxoVSb55zfpCb3Zc56QAd6aRDvGAO26S4Y=,tag:zPdAAsdxCfW4cStiUG4hTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1meu65v2nuw6ntzn8fghgc59mmkcm2uhynj4ydchrpdp6audq2y6q85kadn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdjZIc2NPR0JGeVRXVjRE
            QTBaZ0hGSjR0WG1hUkdTVEVaMUp5Tjg3VUZnCjVua28rS0piYThraXlTU0JjOStU
            UXFHaWpVb0x5Si9PK3lZang2OHNjaUEKLS0tIGlSRnV0VmNYdExuYXJLMjR6SERR
            MGQzUmt0ajBHMWpUcERZTWhqQ3lHYkkKdIwIy6ohCO0UWYNSYAARYGFwa0YMKLP4
            BGielraivvWQWPrDmWKhXPjcU9rbDi/uG2lClmpAT2nKZWkopnqdVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T19:52:22Z"
    mac: ENC[AES256_GCM,data:Lk55zNjjo+84U6hSSQMrJhp37Ma+CPri5t8dt4olinwjaNTL4yIOlKLUxJXP7cAC2qlVVwaL4+477XmIiW+oIRiiRbN4uFULjAgylzqX1EH6oPpW7AtwEgXh0pGv7ZGwSDlhy3Yg1rhKoFqoDo7hNpt44Xgtl+V8TfefMuOjE5M=,iv:8LCDE2fTvXu/Oha/9GhFUluf7mNSwK0JgOTOyiVvTGc=,tag:a+qL+lZzOW/jx46l32zqLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
