apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:LhOsVhReojcsi1ggG94DlxzzFWhgs9OsjF1z84g7oOQ+6LavLJ0RyvcL8n137sbpZ+Toa0cQ4KBOcTdJibBCjIY/QDBlU7zrZbp7OkFkBVTnvGankZ4txsgbIdSu8crrkk1QANT/luYLR10RpPLfaSblTRaISxV4K6u2m77pWS5FXAzXfmIOUwIxRtbHipdgH/ji5psMhO22F8ARR3NC9TJ11r8tm+EiGNQ3xrlBNlOJbDjCoVkPe6DzqYm+429LCiMzvd10IbXo5hVRGMrzQcJYr5HIPTbzOTxLTWq9ye9gLv28Kfy7GuuCTRkrTwzjJZeQM+sQhr7ZdEukCWm+6pecn+0kTJ4C3M5xcyUYjhC7s+axu/7YkUl6hMnH16nwGYKKxs0L9xFDIvl0QeOp7otgfTCRlYqntWr6E3OBg1t+54w8+gtyGXfzCzKCrQ5Covs6Mo01J35gma6WD1b1GXZ/qgu9ebht9prch4eZKZ7SaYhHxPjOLjZFRkac6/VVnBZ0SsnIt7Y2p0kMTIMT5EMEXfoZmg4AjvVfBtzK6rhwG3fK2GRtzH4X2Aqirp3PGDSGxUwHbor/5HcUvycDo/CEHw246SQmY/PSnmSY6tTDnEHK/qGXn82d47ZBYHJfqa5UXLKNtRRr82oTpEI1Ki5LwIWhfVeLcaylbJVQ2Kb79LtvXoVypg2lWvou/icv6gFQo/JbHgv6jDD8BDWjBCi/pdt+0tVvFjriPf1SM3JVhlvvJlTy5ox112iYSysBdyFCH1HAVa6Hg+3rbJhX0eLv7hCi9o3gF1b1oi0WSQwOnrYi3JJIOkJXn7eV1fa7VJLZyHkFj7op8+P7OKXOleQbds4l5mVPu8+iuAN3jAPL1l62a8HsbUt/vIVxBAJnT55Ihm9owifBilyDN5Oi1nNh9jJU1/ReqDymGKPpXSk4/qMrbXToYipHmYJov2aIhQdoRhCrRM40iBVdEdeyLm2Bw5RDXW5iW4eWOLwI5zVoZrpmnxeUUYtddxk=,iv:NPl9P9Hp7hwkZqkbmxJYLG6ROslqRrk9aRrA2FcQCYw=,tag:jKacfIRHLqN84hbaVABfjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1meu65v2nuw6ntzn8fghgc59mmkcm2uhynj4ydchrpdp6audq2y6q85kadn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d3pocDZ5THU3ak1pSnJB
            UXl2TkhrL0tOajRHVSszdEw2am9pMDJ3M2lBCnpaOUpacFJ5T21CMmF1L3hZOGhl
            WGpxTGxESTM3YXRCRzZ3SlBxd1dickkKLS0tIHdtbUMva1JTY2FHUGJsZ1BLYWFv
            eWZFejRiVmlGYzcrbGZLckRteFpXTGsKIiz9rbBZa+baoh6o/OZGA+Nr7D8li7ay
            5XMlF6S+Cr2+1nBkm5Wy0Xr4KW5x6yrdaPsxOkb2sibXsYWC+9iunA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T19:53:01Z"
    mac: ENC[AES256_GCM,data:Bps0x+yTtq7S5U0u1LT6HHpUKSk/0ZKvx0QHGr2LYfH0uAkv04patFunTZU5bCtQ8CKDlzWbPp7KVCRM/JTDPrlvUHMGRHZH34RShNWOJA6ph04632iRa1wf66/1649VbrNiVVdptaDmUsURWYLmOssDQVFxXBPYv2EJ8Q3T3O8=,iv:0l2XK90JIkLGoiyD536otABoBJyCF913we6wxFYU5pM=,tag:KhUzsMAzrESpE/OUBTLvOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
