apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:HcIeXdtgzEtU34ae7lf4Wd8cg1FHQYj892x9p8vs3RVO5PYgb14YNCtEJJ7O58j8kP7y8gPp2fA/OAvw+LyRGFSgMawCHAVroF2i+OVMqDBWmoLxKTCLGhcGnYs3CXHxdWCGR4IVGmjlYGyJUt3HJ3cDlGVl57XhM7ojpwaUnSu97XIKfA0lRp4XsWvORjwVAn300vWZWHdsW7V4mu2kI1joQVxnJr+ZL8B9IXw8ElR+8M/P9KmrjnFJzA/OuB9hQLUOMHr6CN3QwTmXcQ3r3Ic6FAP1q6JphmKOQeG4SkxMcjMYg3+vViF8x4jOrT55w9QNYC9C6T3JDeIcDMZxnLRnB/5aziwwe61W3/ceO1HDqkrTzrRolkb8O/Y/BAR4puQM6twgV52WoIz7BEcwLtpMIQTcly2GuqAUQZWdEQ7fWdwT7XMoZUuQVvDuNAfdYaA5KahTIWCOkeLhqR/PHVm1OrwPeYXZoEk4m3lVCtKStzRah3/Luva0+SCHDSj82DeDq36qztBBhMCBqkC2fKAWmZfD614u6DYbLnpL3bVFGfAWjkFMC5DlnqkVtId+f52Hbb9IMNZFrjADe17FWUacfWF91XIa+ZXvboySojEKqlck87myqZSuJz1mRoIuvkyL4B8l3h6vW9zwBG9ujSKhsCk9scN7ihkwAM1D2bM6ZRPdTKiuigg=,iv:3ncxlJuOHFpy5fQH0FvRWOZSL1Z2Mo00CDS4sIM/dMw=,tag:8prgnmsgQJgvLCkqzswEiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1meu65v2nuw6ntzn8fghgc59mmkcm2uhynj4ydchrpdp6audq2y6q85kadn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6d3pocDZ5THU3ak1pSnJB
            UXl2TkhrL0tOajRHVSszdEw2am9pMDJ3M2lBCnpaOUpacFJ5T21CMmF1L3hZOGhl
            WGpxTGxESTM3YXRCRzZ3SlBxd1dickkKLS0tIHdtbUMva1JTY2FHUGJsZ1BLYWFv
            eWZFejRiVmlGYzcrbGZLckRteFpXTGsKIiz9rbBZa+baoh6o/OZGA+Nr7D8li7ay
            5XMlF6S+Cr2+1nBkm5Wy0Xr4KW5x6yrdaPsxOkb2sibXsYWC+9iunA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T23:08:27Z"
    mac: ENC[AES256_GCM,data:9+UtnFb9G7Hgfxeo+xoXoDEoCjADuTWH/X8zka2bduQ+ghoxM9O6kdkg9w2yVJYPvlX4k0jjaTuYPxB3rX6u/78EajzUqosIPbThHkndiWIzmFPfCY9goykA6BtgIJ8Qs52jvtqIqm3jzxro1gPIEGvGKkaEXqMYDl/zO+qdVWc=,iv:0s/j5uPB/NliYlP+29bakgqhhpc4ARr+Jb3tvKgsZ4c=,tag:9rXYlJqWZqpxiK7on6VX8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
