---
groups:
  - name: smart
    rules:
      - alert: SMARTFailure
        expr: |
          sum by (hostname) (count_over_time({hostname=~".+"} | json | _SYSTEMD_UNIT = "smartmontools.service" !~ "(?i)previous self-test completed without error" !~ "(?i)Prefailure" |~ "(?i)(error|fail)"[2m])) > 0
        for: 2m
        labels:
          severity: critical
          category: logs
        annotations:
          hostname: "{{ $labels.hostname }}"
          summary: "{{ $labels.hostname }} has reported SMART failures"

  - name: plex
    rules:
      - alert: PlexDatabaseBusy
        expr: |
          sum by (app) (count_over_time({app="plex"} |~ "(?i)retry busy DB"[2m])) > 0
        for: 2m
        labels:
          severity: critical
          category: logs
        annotations:
          app: "{{ $labels.app }}"
          summary: "{{ $labels.app }} is experiencing database issues"

  - name: promtail
    rules:
      - alert: PromtailWarning
        expr: |
          sum by (hostname) (count_over_time({hostname="proxmox"}[$__auto] | logfmt | unit="promtail.service" | level="warn")) > 0
        for: 2m
        labels:
          severity: critical
          category: logs
        annotations:
          hostname: "{{ $labels.hostname }}"
          summary: "{{ $labels.hostname }} is experiencing a Promtail warnings that need investigation"
