---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: proxmox-exporters
spec:
  staticConfigs:
    - targets:
        - 192.168.5.10:9100  # node-exporter
        - 192.168.5.10:8080  # cadvisor
        - 192.168.5.10:9221  # pve-exporter
        - 192.168.5.10:9633  # smartctl exporter
        - 192.168.5.10:9558  # systemd exporter
  metricsPath: /metrics
